// 黄梅戏视频库
export default{
  '棒打薄情郎': {
    // src: 'https://cdn.jsdelivr.net/gh/lujiuj/hm-cdn-assents/video/棒打薄情郎.mp4',
    type: 'bilibili',
    bvid:'BV1wb4y1r71T',
    title: '棒打薄情郎',
    description: '黄梅戏传统剧目，讲述女子怒打负心汉的故事，体现了古代女性对爱情的忠贞和对负心行为的抗争',
    tags: ['黄梅戏', '传统', '爱情', '道德', '惩戒'],
    duration: '7:20',
    performers: ['严凤英', '潘璟琍'],
    year: '1962',
    plot: '书生金玉奴在得中功名后嫌弃糟糠之妻，欲另娶高门，其妻在众人支持下用棒槌痛打负心郎，最终使其悔悟',
    highlights: ['激烈的戏剧冲突', '女子反抗负心汉的勇敢行为', '传统道德观念的体现', '大快人心的结局'],
    characters: ['金玉奴', '莫稽', '金父', '媒婆'],
    style: '社会伦理剧',
    singingStyle: '激昂有力，富有戏剧张力',
    culturalSignificance: '反映了传统社会对负心行为的道德批判，展现了女性的觉醒和抗争精神'
  },
  '秤妈': {
    // src: 'https://cdn.jsdelivr.net/gh/lujiuj/hm-cdn-assents/video/秤妈.mp4',
    type: 'bilibili',
    bvid:'BV1gh4y1i7fV', //https://www.bilibili.com/video/BV1gh4y1i7fV?t=4.2
    title: '秤妈',
    description: '黄梅戏现代题材剧目，围绕家庭赡养与孝道展开，批判不孝行为，弘扬传统美德',
    tags: ['黄梅戏', '现代', '家庭', '孝道', '伦理'],
    duration: '6:30',
    performers: ['未知'],
    year: '未知',
    plot: '不孝子嫌弃母亲，用秤称量母亲饭量，引发家庭矛盾，最终在众人教育下幡然醒悟，重拾孝道',
    highlights: ['贴近生活的家庭矛盾', '对不孝行为的辛辣讽刺', '孝道主题的深刻演绎', '接地气的表演风格'],
    characters: ['母亲', '儿子', '儿媳', '乡邻'],
    style: '现代伦理剧',
    singingStyle: '朴实直白，充满生活气息与批判力量',
    culturalSignificance: '聚焦当代家庭赡养问题，呼吁传承孝道，弘扬尊老爱老的传统美德'
  },
  '错配姻缘': {
    // src: 'https://cdn.jsdelivr.net/gh/lujiuj/hm-cdn-assents/video/错配姻缘.mp4',
    type: 'bilibili',
    bvid:'BV1sk4y1S7QM', //https://www.bilibili.com/video/BV1sk4y1S7QM?t=1.5
    title: '错配姻缘',
    description: '黄梅戏传统喜剧，讲述因阴差阳错导致的姻缘错位，最终在波折中成就美满姻缘的故事',
    tags: ['黄梅戏', '传统', '喜剧', '爱情', '姻缘'],
    duration: '8:00',
    performers: ['未知'],
    year: '未知',
    plot: '富家小姐与穷书生因媒婆误传信息而错配姻缘，历经误会与波折后，有情人终成眷属',
    highlights: ['诙谐幽默的误会桥段', '一波三折的姻缘走向', '轻松活泼的喜剧表演', '圆满的爱情结局'],
    characters: ['富家小姐', '穷书生', '媒婆', '双方家长'],
    style: '传统爱情喜剧',
    singingStyle: '轻快俏皮，充满喜剧色彩与生活趣味',
    culturalSignificance: '体现了传统社会对自由爱情的向往，展现了“有情人终成眷属”的美好愿景'
  },
  '窦娥冤': {
    // src: 'https://cdn.jsdelivr.net/gh/lujiuj/hm-cdn-assents/video/窦娥冤.mp4',
    type: 'bilibili',
    bvid:'BV1KE411v7Q4', //https://www.bilibili.com/video/BV1KE411v7Q4?t=5.6
    title: '窦娥冤',
    description: '改编自关汉卿同名杂剧的黄梅戏经典悲剧，讲述窦娥蒙冤受屈、感天动地的悲壮故事',
    tags: ['黄梅戏', '经典', '悲剧', '冤案', '正义'],
    duration: '9:10',
    performers: ['未知'],
    year: '未知',
    plot: '窦娥被无赖诬陷、贪官错判，临刑前许下三桩誓愿以证清白，最终六月飞雪、血溅白练，沉冤得雪',
    highlights: ['感天动地的誓愿场景', '窦娥不屈的抗争精神', '对官场黑暗的深刻批判', '悲壮的悲剧氛围'],
    characters: ['窦娥', '窦天章', '张驴儿', '贪官'],
    style: '古典悲剧',
    singingStyle: '悲愤激昂，充满控诉力量与悲剧感染力',
    culturalSignificance: '中国古典悲剧代表作，揭露了封建司法的黑暗，歌颂了底层人民的反抗精神'
  },
  '赌妻还妻': {
    // src: 'https://cdn.jsdelivr.net/gh/lujiuj/hm-cdn-assents/video/赌妻还妻.mp4',
    type: 'bilibili',
    bvid:'BV1pE411y7i2',//https://www.bilibili.com/video/BV1pE411y7i2?t=3.9
    title: '赌妻还妻',
    description: '黄梅戏警示剧目，讲述嗜赌丈夫输掉妻子后幡然醒悟，最终赢回妻子、浪子回头的故事',
    tags: ['黄梅戏', '传统', '警示', '家庭', '戒赌'],
    duration: '7:40',
    performers: ['未知'],
    year: '未知',
    plot: '丈夫沉迷赌博，将妻子作为赌注输掉，妻子被迫离开后，丈夫痛改前非，靠勤劳努力赢回妻子，重建家庭',
    highlights: ['赌徒的堕落与觉醒', '妻子的坚韧与等待', '戒赌主题的深刻警示', '浪子回头的圆满结局'],
    characters: ['丈夫', '妻子', '赌徒', '乡邻'],
    style: '警示伦理剧',
    singingStyle: '跌宕起伏，兼具悔恨与希望的情感表达',
    culturalSignificance: '批判赌博恶习，警示世人珍惜家庭，弘扬勤劳向善的价值观'
  },
  '九斤姑娘': {
    // src: 'https://cdn.jsdelivr.net/gh/lujiuj/hm-cdn-assents/video/九斤姑娘.mp4',
    type: 'bilibili',
    bvid:'BV1vD421L7sT',//https://www.bilibili.com/video/BV1vD421L7sT?t=3.2
    title: '九斤姑娘',
    description: '黄梅戏经典生活小戏，塑造了聪明伶俐、机智过人的农家少女九斤姑娘形象',
    tags: ['黄梅戏', '小戏', '生活', '智慧', '喜剧'],
    duration: '6:15',
    performers: ['未知'],
    year: '未知',
    plot: '九斤姑娘凭借过人智慧，巧妙化解了邻里纠纷与家庭矛盾，展现了农家少女的聪慧与善良',
    highlights: ['九斤姑娘的机智应变', '充满乡土气息的生活场景', '诙谐幽默的喜剧效果', '朴实的民间智慧'],
    characters: ['九斤姑娘', '父亲', '邻居', '媒婆'],
    style: '生活喜剧小戏',
    singingStyle: '明快活泼，充满乡土气息与民间趣味',
    culturalSignificance: '展现了江南农家生活风貌，歌颂了劳动人民的智慧与乐观精神'
  },
  '苦女冤': {
    // src: 'https://cdn.jsdelivr.net/gh/lujiuj/hm-cdn-assents/video/苦女冤.mp4',
    type: 'bilibili',
    bvid:'BV15t411v7T6',//https://www.bilibili.com/video/BV15t411v7T6?t=2.1
    title: '苦女冤',
    description: '黄梅戏悲情剧目，讲述底层女子遭受欺凌与冤屈，最终在正义帮助下得以昭雪的故事',
    tags: ['黄梅戏', '传统', '悲剧', '冤案', '底层'],
    duration: '8:30',
    performers: ['未知'],
    year: '未知',
    plot: '贫苦女子被恶霸欺凌、诬陷，含冤入狱，在正直乡绅与清官帮助下，最终沉冤得雪，恶人得到惩治',
    highlights: ['底层女子的悲惨遭遇', '正义力量的挺身而出', '对恶霸的有力批判', '沉冤得雪的大快人心'],
    characters: ['苦女', '恶霸', '清官', '正直乡绅'],
    style: '悲情伦理剧',
    singingStyle: '凄婉悲怆，充满对命运的控诉与对正义的呼唤',
    culturalSignificance: '反映了封建社会底层人民的苦难，歌颂了正义与善良，批判了豪强恶霸的恶行'
  },
  '梁祝·楼台会': {
    // src: 'https://cdn.jsdelivr.net/gh/lujiuj/hm-cdn-assents/video/梁祝·楼台会.mp4',
    type: 'bilibili',
    bvid:'BV1ST4y1M7c2',// https://www.bilibili.com/video/BV1ST4y1M7c2?t=3.0
    title: '梁祝·楼台会',
    description: '黄梅戏经典剧目《梁山伯与祝英台》中的楼台相会选段，展现梁山伯与祝英台在楼台相会时的深情对唱',
    tags: ['黄梅戏', '经典', '爱情', '悲剧', '楼台会'],
    duration: '7:20',
    performers: ['韩再芬', '黄新德'],
    year: '1995',
    plot: '祝英台被父亲许配马家后，与梁山伯在楼台相会，两人互诉衷肠，表达对爱情的忠贞不渝，展现了封建礼教下的爱情悲剧',
    highlights: ['楼台相会的深情对唱', '十八相送的回忆', '爱情悲剧的感人演绎', '经典唱段"楼台会"'],
    characters: ['梁山伯', '祝英台'],
    style: '爱情悲剧',
    singingStyle: '哀婉动人，情感真挚深沉',
    culturalSignificance: '中国四大爱情故事之一，展现了传统社会对自由爱情的压抑与抗争'
  },
  '孟姜女': {
    // src: 'https://cdn.jsdelivr.net/gh/lujiuj/hm-cdn-assents/video/孟姜女.mp4',
    type: 'bilibili',
    bvid:'BV1Zs41137q6',//https://www.bilibili.com/video/BV1Zs41137q6?t=2.4
    title: '孟姜女',
    description: '黄梅戏经典剧目《孟姜女》，讲述孟姜女为寻夫哭倒长城的神话爱情故事',
    tags: ['黄梅戏', '经典', '爱情', '悲剧', '神话'],
    duration: '8:15',
    performers: ['马兰', '黄新德'],
    year: '1998',
    plot: '孟姜女的新婚丈夫范杞良被征去修长城，孟姜女千里寻夫，得知丈夫已死，痛哭三天三夜，长城崩塌八百里，露出丈夫尸骨',
    highlights: ['千里寻夫的艰辛历程', '哭倒长城的震撼场景', '坚贞不渝的爱情表达', '反抗暴政的悲壮主题'],
    characters: ['孟姜女', '范杞良', '秦始皇'],
    style: '神话爱情悲剧',
    singingStyle: '悲壮激昂，情感浓烈深沉',
    culturalSignificance: '中国四大民间传说之一，展现了劳动人民对暴政的反抗和对忠贞爱情的赞颂'
  },
  '踏青': {
    // src: 'https://cdn.jsdelivr.net/gh/lujiuj/hm-cdn-assents/video/踏青.mp4',
    type: 'bilibili',
    bvid:'BV17t411Y7R7',//https://www.bilibili.com/video/BV17t411Y7R7?t=14.2
    title: '踏青',
    description: '黄梅戏生活小戏，描绘春日踏青时青年男女相遇相知的纯真故事，充满生活情趣和青春气息',
    tags: ['黄梅戏', '小戏', '生活', '青春', '爱情'],
    duration: '5:45',
    performers: ['严凤英', '张云风'],
    year: '1958',
    plot: '春日踏青时节，青年男女在郊外相遇，通过对歌和对话互生情愫，展现了纯真的爱情和美好的青春时光',
    highlights: ['生动的对歌场景', '浓郁的春日气息', '青春活力的表演', '朴实真挚的情感表达'],
    characters: ['春兰', '李生', '小姑'],
    style: '生活抒情小戏',
    singingStyle: '轻快活泼，富有生活气息和青春活力',
    culturalSignificance: '展现了传统民间生活的美好画面，体现了青年男女纯真爱情和生活的诗意'
  },
  '天女散花': {
    // src: 'https://cdn.jsdelivr.net/gh/lujiuj/hm-cdn-assents/video/天女散花.mp4',
    type: 'bilibili',
    bvid:'BV18g4y1t7dV',//https://www.bilibili.com/video/BV18g4y1t7dV?t=2.4
    title: '天女散花',
    description: '改编自佛教故事的黄梅戏神话剧目，展现天女散花、普度众生的唯美场景',
    tags: ['黄梅戏', '神话', '唯美', '宗教', '舞蹈'],
    duration: '6:00',
    performers: ['未知'],
    year: '未知',
    plot: '天女奉佛祖之命，下凡散花以检验弟子修行，花瓣飘落之处，众生皆受感化，展现了佛法的慈悲与美好',
    highlights: ['唯美的散花舞蹈场景', '空灵飘逸的唱腔', '充满禅意的舞台表现', '神话与艺术的完美融合'],
    characters: ['天女', '佛祖', '众弟子'],
    style: '神话歌舞剧',
    singingStyle: '空灵飘逸，富有禅意与唯美意境',
    culturalSignificance: '将佛教故事与黄梅戏艺术结合，展现了传统戏曲的唯美表现力与文化包容性'
  },
  '天仙配-鹊桥': {
    // src: 'https://cdn.jsdelivr.net/gh/lujiuj/hm-cdn-assents/video/天仙配-鹊桥.mp4',
    type: 'bilibili',
    bvid:'BV1NT57zkErC',// https://www.bilibili.com/video/BV1NT57zkErC?t=3.2
    title: '天仙配-鹊桥',
    description: '黄梅戏经典剧目《天仙配》的鹊桥相会选段，讲述七仙女与董永在七夕鹊桥重逢的感人场景',
    tags: ['黄梅戏', '经典', '爱情', '神话', '鹊桥'],
    duration: '7:00',
    performers: ['严凤英', '王少舫'],
    year: '1955',
    plot: '七仙女被天庭召回后，与董永约定每年七夕在鹊桥相会，两人隔河相望，互诉思念，展现了坚贞不渝的爱情',
    highlights: ['鹊桥相会的浪漫场景', '经典对唱“夫妻双双把家还”片段', '神话爱情的唯美演绎', '对自由爱情的歌颂'],
    characters: ['七仙女', '董永', '牛郎', '织女（客串）'],
    style: '神话爱情剧',
    singingStyle: '深情婉转，充满思念与期盼的情感',
    culturalSignificance: '中国四大民间传说之一，《天仙配》是黄梅戏代表作，歌颂了劳动人民的纯真爱情与反抗精神'
  },
  '神算记': {
    // src: 'https://cdn.jsdelivr.net/gh/lujiuj/hm-cdn-assents/video/神算记.mp4',
    type: 'bilibili',
    bvid:'BV1iv411g7Fi',//https://www.bilibili.com/video/BV1iv411g7Fi?t=2.3
    title: '神算记',
    description: '黄梅戏喜剧剧目，讲述“神算”先生误打误撞解决民间难题，最终揭露骗局的故事',
    tags: ['黄梅戏', '喜剧', '智慧', '讽刺', '民间'],
    duration: '7:30',
    performers: ['未知'],
    year: '未知',
    plot: '自称“神算”的江湖术士靠骗术谋生，却在一次算命中误打误撞破解了民间悬案，最终在真相面前幡然醒悟，弃骗从良',
    highlights: ['诙谐幽默的算卦场景', '误打误撞的喜剧反转', '对江湖骗术的辛辣讽刺', '小人物的觉醒与成长'],
    characters: ['神算先生', '乡民', '受害者', '县官'],
    style: '民间讽刺喜剧',
    singingStyle: '俏皮诙谐，充满讽刺意味与生活趣味',
    culturalSignificance: '批判封建迷信与江湖骗术，歌颂了劳动人民的智慧与求真精神'
  },
  '柳玉娘': {
    // src: 'https://cdn.jsdelivr.net/gh/lujiuj/hm-cdn-assents/video/柳玉娘.mp4',
    type: 'bilibili',
    bvid:'BV1Mt411v7X7',//https://www.bilibili.com/video/BV1Mt411v7X7?t=3.2
    title: '柳玉娘',
    description: '黄梅戏经典剧目，塑造了聪慧勇敢、重情重义的女子柳玉娘形象，展现了她的人生波折与情感抉择',
    tags: ['黄梅戏', '经典', '女性', '爱情', '侠义'],
    duration: '8:20',
    performers: ['未知'],
    year: '未知',
    plot: '柳玉娘出身贫寒，却聪慧过人，在乱世中与书生相知相爱，又为救恩人挺身而出，最终成就了侠义与爱情的圆满',
    highlights: ['柳玉娘的聪慧与勇敢', '跌宕起伏的情感纠葛', '侠义精神的生动演绎', '女性形象的鲜明塑造'],
    characters: ['柳玉娘', '书生', '恩人', '反派'],
    style: '侠义爱情剧',
    singingStyle: '刚柔并济，兼具柔情与侠义的情感张力',
    culturalSignificance: '塑造了传统戏曲中少见的“侠女”形象，歌颂了女性的智慧、勇气与情义'
  },
  '寿堂风波': {
    // src: 'https://cdn.jsdelivr.net/gh/lujiuj/hm-cdn-assents/video/寿堂风波.mp4',
    type: 'bilibili',
    bvid:'BV1Su4y1j7En',//https://www.bilibili.com/video/BV1Su4y1j7En?t=2.6
    title: '寿堂风波',
    description: '黄梅戏家庭伦理剧，围绕老人寿宴展开，揭露家庭内部矛盾，最终化解误会、重归于好',
    tags: ['黄梅戏', '现代', '家庭', '伦理', '和解'],
    duration: '6:45',
    performers: ['未知'],
    year: '未知',
    plot: '老人寿宴上，因财产分配与赡养问题引发家庭风波，在长辈与乡邻的调解下，子女们幡然醒悟，重归于好',
    highlights: ['寿宴上的激烈冲突', '家庭矛盾的真实写照', '亲情与利益的抉择', '和解圆满的结局'],
    characters: ['老寿星', '长子', '次子', '女儿', '乡邻'],
    style: '现代家庭伦理剧',
    singingStyle: '朴实真挚，充满生活气息与情感张力',
    culturalSignificance: '聚焦当代家庭矛盾，呼吁亲情回归，弘扬尊老爱幼、家庭和睦的传统美德'
  },
  '七世夫妻': {
    // src: 'https://cdn.jsdelivr.net/gh/lujiuj/hm-cdn-assents/video/七世夫妻.mp4',
    type: 'bilibili',
    bvid:'BV1pzAEzJE9V',//https://www.bilibili.com/video/BV1pzAEzJE9V?t=2.8
    title: '七世夫妻',
    description: '黄梅戏神话爱情剧，讲述一对恋人历经七世轮回、始终不离不弃的爱情传奇',
    tags: ['黄梅戏', '神话', '爱情', '轮回', '忠贞'],
    duration: '9:00',
    performers: ['未知'],
    year: '未知',
    plot: '一对恋人因反抗封建礼教被迫殉情，魂魄相约历经七世轮回，每一世都遭遇磨难却始终坚守爱情，最终修成正果',
    highlights: ['跨越七世的爱情传奇', '跌宕起伏的轮回故事', '对忠贞爱情的极致歌颂', '神话与爱情的完美融合'],
    characters: ['恋人（七世形象）', '月老', '判官', '反派'],
    style: '神话爱情悲剧',
    singingStyle: '缠绵悱恻，充满宿命感与忠贞不渝的情感',
    culturalSignificance: '以神话形式表达了对永恒爱情的向往，体现了传统爱情观中“生死相随”的极致浪漫'
  },
  '三请樊梨花': {
    // src: 'https://cdn.jsdelivr.net/gh/lujiuj/hm-cdn-assents/video/三请樊梨花.mp4',
    type: 'bilibili',
    bvid:'BV1KU4y1475q',//https://www.bilibili.com/video/BV1KU4y1475q?t=5.7
    title: '三请樊梨花',
    description: '黄梅戏历史战争剧，讲述薛丁山三请樊梨花出山，共同平定战乱的故事，塑造了巾帼英雄樊梨花形象',
    tags: ['黄梅戏', '历史', '战争', '巾帼英雄', '忠义'],
    duration: '8:40',
    performers: ['未知'],
    year: '未知',
    plot: '薛丁山因误会休妻，后战事吃紧，三次亲自恳请樊梨花出山，樊梨花以家国为重，不计前嫌挂帅出征，平定战乱',
    highlights: ['樊梨花的巾帼英雄气概', '三请樊梨花的曲折过程', '家国大义与个人恩怨的抉择', '精彩的战争场面演绎'],
    characters: ['樊梨花', '薛丁山', '程咬金', '敌军将领'],
    style: '历史战争剧',
    singingStyle: '高亢激昂，充满英雄气概与家国情怀',
    culturalSignificance: '塑造了经典巾帼英雄形象，歌颂了女性的军事才能与家国大义，体现了传统忠义观'
  },
  '双龙配双凤': {
    // src: 'https://cdn.jsdelivr.net/gh/lujiuj/hm-cdn-assents/video/双龙配双凤.mp4',
    type: 'bilibili',
    bvid:'BV15m411Q7Yn',//https://www.bilibili.com/video/BV15m411Q7Yn?t=8.2
    title: '双龙配双凤',
    description: '黄梅戏传统爱情喜剧，讲述两对青年男女因机缘巧合相识相知，最终成就两段美好姻缘的故事',
    tags: ['黄梅戏', '传统', '喜剧', '爱情', '姻缘'],
    duration: '7:10',
    performers: ['未知'],
    year: '未知',
    plot: '两位龙姓公子与两位凤姓女子在庙会相遇，历经误会与撮合，最终两对有情人终成眷属，成就“双龙配双凤”的美满姻缘',
    highlights: ['诙谐幽默的误会桥段', '两对青年的情感纠葛', '热闹喜庆的喜剧氛围', '圆满的姻缘结局'],
    characters: ['龙大公子', '龙二公子', '凤大小姐', '凤二小姐', '媒婆'],
    style: '传统爱情喜剧',
    singingStyle: '轻快活泼，充满喜庆气息与民间趣味',
    culturalSignificance: '体现了传统社会对“天作之合”美好姻缘的向往，展现了民间爱情喜剧的独特魅力'
  }
};